"""add_nickname_to_api_keys

Revision ID: 298dfa411abf
Revises: 66d3292887e3
Create Date: 2025-07-14 18:41:27.710525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298dfa411abf'
down_revision: Union[str, None] = '66d3292887e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add the column as nullable first
    op.add_column('user_api_keys', sa.Column('nickname', sa.String(length=100), nullable=True))
    # 2. Set all existing rows to "default"
    op.execute("UPDATE user_api_keys SET nickname = 'default'")
    # 3. Alter the column to be non-nullable
    op.alter_column('user_api_keys', 'nickname', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_api_keys', 'nickname')
    # ### end Alembic commands ###
