"""New auth id for user

Revision ID: a4c0ad6e7dff
Revises: 5268a074bb15
Create Date: 2025-06-07 16:25:20.117996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c0ad6e7dff'
down_revision: Union[str, None] = '5268a074bb15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user', ['auth_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'auth_id')
    # ### end Alembic commands ###
