"""store chat history

Revision ID: ac7291795ae2
Revises: a4c0ad6e7dff
Create Date: 2025-06-08 17:10:01.012573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7291795ae2'
down_revision: Union[str, None] = 'a4c0ad6e7dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debate', sa.Column('pro_chat_history', sa.JSON(), nullable=True))
    op.add_column('debate', sa.Column('con_chat_history', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debate', 'con_chat_history')
    op.drop_column('debate', 'pro_chat_history')
    # ### end Alembic commands ###
